services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: teleexam-postgres

    environment:
      POSTGRES_USER: teleexam
      POSTGRES_PASSWORD: teleexam123
      POSTGRES_DB: teleexam

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: teleexam-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: