"""add learner profiles table

Revision ID: 377b79dc45a1
Revises: 5d908fe32ea4
Create Date: 2026-07-30 19:26:13.190181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377b79dc45a1'
down_revision: Union[str, None] = '5d908fe32ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('curriculum_chunks_embedding_hnsw_idx', table_name='curriculum_chunks', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('curriculum_chunks_embedding_hnsw_idx', 'curriculum_chunks', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
