"""add learner profiles table

Revision ID: da3a7466e408
Revises: 377b79dc45a1
Create Date: 2026-07-30 19:29:12.039261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da3a7466e408'
down_revision: Union[str, None] = '377b79dc45a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('weak_topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('avg_score', sa.Integer(), nullable=False),
    sa.Column('exams_done', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_telegram_id'), 'learner_profiles', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_profiles_telegram_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    # ### end Alembic commands ###
